repos:
-   repo: https://github.com/psf/black
    hooks:
    rev: 22.6.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/pylint
    hooks:
    rev: pylint-2.6.0
    hooks:
    -   id: pylint

 
