repos:
-   repo: https://github.com/psf/black
    hooks:
    rev: 22.6.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/pylint
    rev: v2.14.5
    hooks:
    -   id: pylint
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.15  
  hooks:
  - id: mdformat
    additional_dependencies:
    - mdformat-gfm
    - mdformat-black
 