repos:
-   repo: https://github.com/psf/black
    hooks:
    rev: 22.6.0
    hooks:
    -   id: black
        args: # arguments to configure black
            - --line-length=88
-   repo: https://github.com/pycqa/pylint
    rev: v2.14.5
    hooks:
    -   id: pylint
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.0
    hooks:
    -   id: prettier
  