# Github action to cleanup a PR preview
#  Runs when a pull request comment contains '#delete_preview'
#

name: PR Preview Cleanup

on:
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body,'#delete_preview')
    
    steps:

    # Checkout existing gh-pages branch into PUBLISH_DIR
    - name: Checkout gh-pages
      uses: actions/checkout@v2
      with:
        path: gh-pages
        ref: 'gh-pages'

    # Cleanup preview files
    - name: PR Cleanup
      run: |
        rm -rf pr/${{github.event.issue.number}}
        
    - name: Commit files # transfer the new html files back into the repository
      run: |
        git config --local user.name "henilp105" 
        git add pr
        git commit -m "Delete preview build for PR"
    - name: Push changes # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.API_GITHUB_TOKEN }}
        force: true
    
    # Comment on pull request 
    - name: Comment on pull request
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{github.event.issue.number}}
        body: The preview build for this PR has now been deleted.
