# Github action to build sphinx site and commit to gh-pages branch
#
#  Built site is pushed to 'gh-pages' branch
#

name: Sphinx Preview Build

on:
  workflow_dispatch:
  issue_comment:
    types: [created]

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body,'#build_preview')
    
    steps:
    - name: Checkout pr/${{github.event.issue.number}}
      uses: actions/checkout@v2
      
    - name: Fetch pr/${{github.event.issue.number}}
      run: |
        git fetch origin pull/${{github.event.issue.number}}/head:pr-${{github.event.issue.number}}
        git checkout pr-${{github.event.issue.number}}
      
    - name: Setup Python
      uses: actions/setup-python@v1

    - name: Install sphinx
      run: pip3 install --user -r requirements.txt
      
    - name: Build page
      run: make html LANGUAGES=en
      
    - run: touch build/html/.nojekyll

    - name: Deploy documentation sphinx
      uses: JamesIves/github-pages-deploy-action@v4.4.0
      with:
        token: ${{ secrets.API_GITHUB_TOKEN }}
        branch: gh-pages
        target-folder: pr/${{github.event.issue.number}}
        folder: build/html
        clean: false
